spring:
  datasource:
    url: jdbc:mysql://localhost:3306/travel_planner?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root

logging:
  level:
    com.vinn.travelmanager: debug
    org.springframework.web: info

